add a check to nrsconfig if env-vars CC, CXX and FC are at least defined

diff --git a/nrsconfig b/nrsconfig
--- a/nrsconfig
+++ b/nrsconfig
@@ -3,6 +3,12 @@ set -e -a
 
 : ${NRSCONFIG_NOBUILD:=0}
 
+if [ -z ${CC} ] || [ -z ${CXX}  ] || [ -z ${FC}  ]; then
+  echo -e "\033[31mERROR: env-var CC, CXX or FC is not set!\033[m"
+  echo "Please try again using e.g. CC=mpicc CXX=mpic++ FC=mpif77 ./nrsconfig"
+  exit 1
+fi
+
 cmd="cmake -S . -B build -Wfatal-errors $@" 
 echo $cmd
 eval $cmd 
